version: '3.8'

services:
  backend:
    build:
      context: ./beyond-ball-be
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/diss
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgras
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - database

  frontend:
    build:
      context: ./beyond-ball-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgras
      POSTGRES_DB: diss
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: