export const WHITEBOARDS_PAGE = "/whiteboards"
export const TEAM_PAGE = "/team"
export const PROFILE_PAGE = "/profile"
export const CLIPS_PAGE = "/clips"
export const QUIZZES_PAGE = "/quizzes"
export const LOGIN_PAGE = "/"